### PR TITLE
Trigger rebuild of Python 3.6.7

### PR DESCRIPTION
**Pull request by tadeu**
#228

### CODE REVIEW

**Comment by tadeu** [comment]
@conda-forge-admin, please rerender

**Comment by tadeu** [comment]
@conda-forge/core, should I increase the build number here since there was a rerender? The idea is to publish only the win-64 package, since Linux and macOS seems ok.

**Comment by jjhelmus** [comment]
I triggered a rebuild of AppVeyor run from #228.  If that doesn't upload the package merging this without the build number bump is the correction plan of action IMHO.

**Comment by jjhelmus** [comment]
The rebuild failed again, merging this to see if that address the issue.

**Comment by tadeu** [comment]
Didn't work as well :/
Moving the discussion to #228

**Pull request merged**
