### PR TITLE
Update to 3.9.17

### PR DESCRIPTION
**Pull request by nlhnt**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by nlhnt** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
Thanks Marcin! 🙏

Can you please [go through these steps to refresh the patches]( https://github.com/conda-forge/python-feedstock/tree/main/recipe/patches#how-to-re-generate-patches )?

**Comment by nlhnt** [comment]
@jakirkham sure, I'll try it today afternoon (CET) :).

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render

**Comment by jakirkham** [comment]
Went ahead and refreshed the patches above. Hope that is ok :)

**Comment by jakirkham** [comment]
Thanks again Marcin! 🙏

**Pull request merged**
