### PR TITLE
Python 3.5.2

### PR DESCRIPTION
**Pull request by jjhelmus**
Update recipe to Python 3.5.2, resetting the build number to 0

Pinnings were reformatted and the sqlite and xz pins were updated to reflect
the upcoming changes to conda-forge's recommendations.

### CODE REVIEW

**Comment by ocefpaf** [comment]
> Pinnings were reformatted and the sqlite and xz pins were updated to reflect
the upcoming changes to conda-forge's recommendations.

I am :+1: to this, but let's wait for https://github.com/conda-forge/conda-forge.github.io/pull/175 and @pelson's opinion on this.

**Comment by jjhelmus** [comment]
Updates to pins as proposed in conda-forge/conda-forge.github.io#175.  
Specifically:
* `xz` changed from `5.0.*` to `5.2.*`
* `sqlite` changed from `3.9.*` to `3.13.*`
* Other package version formatter and sorted.

[Python 3.5.2 Release notice](https://www.python.org/download/releases/3.5.2/)
[Python 3.5.2 Downloads](https://www.python.org/downloads/release/python-352/)
[Python 3.5.2 Change log](https://docs.python.org/3.5/whatsnew/changelog.html#python-3-5-2)

**Comment by jjhelmus** [comment]
> I am 👍 to this, but let's wait for conda-forge/conda-forge.github.io#175 and @pelson's opinion on this.

Agreed, wanted to put this in with the updates to test if the new versions are working.  I can back these down if we want to merge this before the pinnings update is approved.

**Comment by pelson** [comment]
No matter what, I prefer to separate the two issues. The pinned versions don't need updating (but can certainly be correctly sorted!) in order to move to v3.5.2 so let's put that PR in and merge it. We can then open a subsequent PR with the newer pinnings and merge once https://github.com/conda-forge/conda-forge.github.io/pull/175 is in.

**Comment by jjhelmus** [comment]
Changed this PR so that in pins `xz` and `sqlite` to the currently suggested versions.

**Comment by pelson** [comment]
:+1:

**Comment by jjhelmus** [comment]
green :tada:, any other suggestions or reviews?

**Comment by pelson** [comment]
Nope. It is green, and non-controversial. The pinning PR may need some more thought though :smile:

**Comment by jjhelmus** [comment]
Thanks @pelson

**Pull request merged**
