### PR TITLE
3.11.0rc2

### PR DESCRIPTION
**Pull request by chrisburr**
Based on https://github.com/conda-forge/python-feedstock/pull/577 with the downstream tests disabled due to solvability issues.

### CODE REVIEW

**Comment by chrisburr** [comment]
I've build down to scipy on linux-64 using this and everything seems to be working.

**Comment by isuruf** [comment]
> Based on https://github.com/conda-forge/python-feedstock/pull/577 with the downstream tests disabled due to solvability issues.

This is probably a conda-mambabuild bug? Can you check to see if plain conda-build works?

**Comment by chrisburr** [comment]
> This is probably a conda-mambabuild bug. Can you check to see if plain conda-build works?

I tried both and they both failed with different issues.

**Comment by raulcd** [comment]
hi! thanks for the work!
I this going to be discarded and just wait for the official 3.11 release expected next week? or is a 3.11.0rc2 still planned to be available. Thanks!

**Comment by isuruf** [comment]
Closing in favour of #577

**Pull request closed without merging**
