### PR TITLE
Python 1.0.1

### PR DESCRIPTION
**Pull request by jjhelmus**
[skip appveyor]

### CODE REVIEW

**Comment by jjhelmus** [comment]
This should not be merged into master rather into a "version" branch.  I believe this must be done during the merge rather than in the pull request.

**Comment by jakirkham** [comment]
Woah! What?

Should we maybe not put this into `master` if this is happening?

**Comment by jakirkham** [comment]
Sorry, I think we posted at the same time. So, we can add a new branch for `1.x` that you can PR against. Would you like to do this?

**Comment by jjhelmus** [comment]
That will work, my plan was to push this branch to upstream/1.0 if the CIs pass

**Comment by jakirkham** [comment]
Alright, let me create a branch and then we can move the PR over to it.

**Comment by jakirkham** [comment]
Alright, there is a `1.0` branch that is at the same point as `master`. Could we please PR against that instead?

**Comment by jjhelmus** [comment]
Also in case anyone is interests the python-1.0.1 package in `defaults` does not properly set `sys.path` which means most of the "standard library" is not available... although I don't really think this will ever effect anyone.

**Comment by jjhelmus** [comment]
I'll look into the OS X issue and submit a new PR against the `1.0` branch.

**Pull request closed without merging**
