### PR TITLE
Use our build of nasm

### PR DESCRIPTION
**Pull request by jakirkham**
Instead of downloading the binary for `nasm` from CPython. Just use our build of it.

### CODE REVIEW

**Comment by jjhelmus** [comment]
LGTM. Should the build number be bumped to trigger the creation of a new package or should we wait until another change since there should be no difference in the produced binary?

**Comment by jakirkham** [comment]
Either way. Do you have a preference?

**Comment by jjhelmus** [comment]
Merging as is. I want to include a patch for better mingw support today which will require a rebuild.

**Comment by jjhelmus** [comment]
thanks for the update @jakirkham

**Comment by jakirkham** [comment]
Sounds good. Thanks @jjhelmus.

Would it be worthwhile to do something similar for the other Python versions? Interested in avoiding downloading binaries that we haven't built if possible. Though it doesn't look like it would be as easy in the other cases.

**Pull request merged**
