### PR TITLE
Update recipe to Python 3.6.0a4

### PR DESCRIPTION
**Pull request by jjhelmus**
Make version and sha256 Jinja variables

### CODE REVIEW

**Comment by jjhelmus** [comment]
Not sure what is going on with the Windows build but will investigate later tonight.  


Error:
```
compiling .pyc files...
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:
    https://github.com/conda/conda-build/issues
Include the output of the command 'conda info' in your report.
Traceback (most recent call last):
  File "C:\conda\Scripts\conda-build-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\conda\lib\site-packages\conda_build\main_build.py", line 152, in main
    args_func(args, p)
  File "C:\conda\lib\site-packages\conda_build\main_build.py", line 415, in args_func
    args.func(args, p)
  File "C:\conda\lib\site-packages\conda_build\main_build.py", line 358, in execute
    debug=args.debug)
  File "C:\conda\lib\site-packages\conda_build\build.py", line 646, in build
    preserve_egg_dir=bool(m.get_value('build/preserve_egg_dir')))
  File "C:\conda\lib\site-packages\conda_build\post.py", line 182, in post_process
    compile_missing_pyc(files)
  File "C:\conda\lib\site-packages\conda_build\post.py", line 174, in compile_missing_pyc
    call([python_exe, '-Wi', '-m', 'py_compile'] + compile_files, cwd=cwd)
  File "C:\conda\lib\subprocess.py", line 557, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\conda\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "C:\conda\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 206] The filename or extension is too long
```

**Comment by jjhelmus** [comment]
I believe the broken Windows build is caused by the post build step which tries to compile all the .py files at the same time. Best guess is either the filenames are getting mangled or Windows is running out of file handles. If I change the post build logic to a loop to compile the files one at a time then the build on Windows works.

Once the changes in conda/conda-build#1186, which compiles .py files one at a time, make it into a conda-build release a Windows build should be possible.

cc @msarahan

**Comment by jjhelmus** [comment]
Removing the `Lib/test` directory seems to have fixed the Windows build issue.  My guess is that with fewer files to compile Windows no longer runs out of file handlers.  Either way this is ready for review.

**Comment by msarahan** [comment]
Cool. I'll tag a release soon. Probably tomorrow, but depends on a couple of PRs.

**Comment by msarahan** [comment]
Good catch on the python3.6 always_include.  This looks fine to me.  I'll merge here.

Do you think we should restore the Lib/test directory when conda-build is fixed?

**Comment by jjhelmus** [comment]
> Do you think we should restore the Lib/test directory when conda-build is fixed?

I do not think there is a need to include this directory. It contains unit tests for the standard library and does not seem to be included in Unix like installs.  The `conda-forge` Python 2.7 package is also [removing this directory](https://github.com/conda-forge/python-feedstock/blob/caeee50286a708cb899cd675ddee41c1773140a1/recipe/bld.bat#L132-L135) and I think this change should also be added to the Python 3.4 and 3.5 recipes.

**Pull request merged**
