### PR TITLE
WIP: Fix windows 64-bit build

### PR DESCRIPTION
**Pull request by jjhelmus**

### CODE REVIEW

**Comment by pelson** [comment]
Nothing changed in this PR... ?

**Comment by jakirkham** [comment]
I believe @jjhelmus was just trying to make the failure reported in issue ( https://github.com/conda-forge/python-feedstock/issues/10 ) more obvious and potentially start fixing it as time presented itself.

**Comment by jjhelmus** [comment]
Yup, nothing was changed in this PR, I justed wanted to verify that the windows builds really was broken and not some one-off issue.  Also having a broken build to start with seems helpful.

**Comment by jjhelmus** [comment]
I believe the issue with the Windows build is that the wrong version of Visual Studio is being used.  

The [obvci_appveyor_python_build_env.cmd](https://github.com/pelson/Obvious-CI/blob/master/scripts/obvci_appveyor_python_build_env.cmd) script from [Obvious-CI](https://github.com/pelson/Obvious-CI) is responsible for setting the correct environment variables to select the Visual Studio version, this script might need some updates.  The [run_with_env.cmd](https://github.com/ogrisel/python-appveyor-demo/blob/master/appveyor/run_with_env.cmd) script from [ogrisel/python-appveyor-demo](https://github.com/ogrisel/python-appveyor-demo) is a good reference on how these should properly be set.

**Comment by msarahan** [comment]
I'm not sure that script is relevant.  Conda-build has its own version selection logic.  Is that going wrong?

Note that conda-build 1.20.3 should have pretty good logic, but early versions were spotty.

**Comment by jjhelmus** [comment]
@msarahan Yes, I believe you are correct, the issue is with the conda-build package.  

The [last working build](https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.2170/job/qm65xfec72baioc9) from staged-recipes used conda-build 1.20.3 which seems to set only a few environmental variable:

```
[00:01:24] : C:\Miniconda-x64\conda-bld\work\Python-3.5.1
[00:01:24] 
[00:01:24] C:\Miniconda-x64\conda-bld\work\Python-3.5.1>set VS_VERSION="14.0" 
[00:01:24] 
[00:01:24] C:\Miniconda-x64\conda-bld\work\Python-3.5.1>set VS_MAJOR="14" 
[00:01:24] 
[00:01:24] C:\Miniconda-x64\conda-bld\work\Python-3.5.1>set VS_YEAR="2015" 
[00:01:24] 
[00:01:24] C:\Miniconda-x64\conda-bld\work\Python-3.5.1>set CMAKE_GENERATOR="Visual Studio 14 2015 Win64" 
[00:01:24] 
[00:01:24] C:\Miniconda-x64\conda-bld\work\Python-3.5.1>call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64 
[00:01:25] 
[00:01:25] C:\Miniconda-x64\conda-bld\work\Python-3.5.1>set INCLUDE=C:\Miniconda-x64\envs\_build\Library\include;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE;C:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\ucrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\winrt; 
[00:01:25] 
[00:01:25] C:\Miniconda-x64\conda-bld\work\Python-3.5.1>set LIB=C:\Miniconda-x64\envs\_build\Library\lib;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.10586.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.10586.0\um\x64; 
```

The [failing builds](https://ci.appveyor.com/project/conda-forge/python-feedstock/build/1.0.20/job/ty9ilui242qmixm4) are using conda-build 1.20.3 which is setting a much larger number of environmental variables, many of which point to non-existant paths and I think are breaking the build.  I can't tell if these settings are coming from conda-build or elsewhere.

```
[00:04:27] C:\conda\conda-bld\work\Python-3.5.1>set "SYSTEMDRIVE=C:" 
[00:04:27] 
[00:04:27] C:\conda\conda-bld\work\Python-3.5.1>set "PERL_VER=5.18.2" 
[00:04:27] 
[00:04:27] C:\conda\conda-bld\work\Python-3.5.1>set "FRAMEWORKVERSION=v4.0.30319" 
[00:04:27] 
[00:04:27] C:\conda\conda-bld\work\Python-3.5.1>set "APPVEYOR_JOB_NAME=Environment: TARGET_ARCH=x64, CONDA_PY=351" 
[00:04:27] 
[00:04:27] C:\conda\conda-bld\work\Python-3.5.1>set "CHOCOLATEYINSTALL=C:\ProgramData\chocolatey" 
[00:04:27] 
[00:04:27] C:\conda\conda-bld\work\Python-3.5.1>set "SET_SDK_64=Y" 
...
[00:04:27] C:\conda\conda-bld\work\Python-3.5.1>set "VS_VERSION=14.0" 
[00:04:27] 
[00:04:27] C:\conda\conda-bld\work\Python-3.5.1>set "VS_MAJOR=14" 
[00:04:27] 
[00:04:27] C:\conda\conda-bld\work\Python-3.5.1>set "VS_YEAR=2015" 
[00:04:27] 
[00:04:27] C:\conda\conda-bld\work\Python-3.5.1>set "CMAKE_GENERATOR=Visual Studio 14 2015 Win64" 
[00:04:27] 
[00:04:27] C:\conda\conda-bld\work\Python-3.5.1>set "MSYS2_ARG_CONV_EXCL=/AI;/AL;/OUT;/out;" 
[00:04:27] 
[00:04:27] C:\conda\conda-bld\work\Python-3.5.1>set "MSYS2_ENV_CONV_EXCL=CL" 
```

**Comment by msarahan** [comment]
Some time ago, conda-build took all environment variables from the parent shell, and dumped them into a temporary bld.bat.  I changed that to just pass the environment to subprocess, which had the same net effect.  I reverted back to writing the environment variables because it was easier to debug recipes.  Functionally, it should be equivalent.  It's just a question of order of operations: are the VS activation scripts running before or after the env vars are set?  I think after is the right place.

**Comment by jjhelmus** [comment]
For my own benefit, [a table of MSVC versions](http://matthew-brett.github.io/pydagogue/python_msvc.html).  

For Python 3.5 we want to use:

```
VC++ version: 14.0
_MSC_VER: 1900
Alternative Name: Visual Studio 2015
C runtime: ucrtbase.dl and vcruntime140.dll
C++ runtime: 	MSVCP140.DLL
```

**Comment by jjhelmus** [comment]
> just a question of order of operations: are the VS activation scripts running before or after the env vars are set? I think after is the right place.

The activation script is being run BEFORE conda build is executed.  For what I can tell this has always been the case.

**Comment by jjhelmus** [comment]
Why is `obvious-ci-0.5.1` being installed from the [pelson channel](https://ci.appveyor.com/project/conda-forge/python-feedstock/build/1.0.20/job/ty9ilui242qmixm4#L35)? Version 0.6.1 is available in conda-forge?  Looks like appveyor.yml is pulling from pelson/channel/development.

**Comment by jjhelmus** [comment]
:tada: :tada: :tada: [working win-64 build](https://ci.appveyor.com/project/JonathanHelmus/python-feedstock/build/1.0.2/job/yr6s0jvk0len7n73)
After a number of red herrings the actually cause of the issue is that the ` obvci_appveyor_python_build_env.cmd` script does not parse `CONDA_PY` with a value of `351` properly. `35` and `3.5.1` should both be valid but `351` is just wrong.

**Comment by jjhelmus** [comment]
Regenerating this feedstock in an environment which includes a version of conda-build-all with SciTools/conda-build-all#40, should fix the CONDA_PY issue.  Will be submitting a new PR with this more logic solution shortly.

**Pull request closed without merging**
