### PR TITLE
libffi34 for 3.7

### PR DESCRIPTION
**Pull request by ocefpaf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@isuruf, keeping the fingers crossed here. If this works I'll try 3.8 and 3.9 later. Do you mind taking a quick look?

**Comment by isuruf** [comment]
We need to copy https://github.com/conda-forge/python-feedstock/blob/3.6/.ci_support/migrations/libffi34.yaml too

**Comment by ocefpaf** [comment]
> We need to copy https://github.com/conda-forge/python-feedstock/blob/3.6/.ci_support/migrations/libffi34.yaml too

That is in there, that is why the re-rendering worked, but I forgot to commit. Just a sec...

**Review by isuruf — APPROVED** [review]

**Comment by ocefpaf** [comment]
@isuruf should we worry about Travis-CI ppcle64 here? Or is it OK to merge it without this arch?

**Comment by isuruf** [comment]
that's a network error. we can merge without it

**Pull request merged**
