### PR TITLE
Fix aarch64 sysconfig file for Python 2.7

### PR DESCRIPTION
**Pull request by jjhelmus**

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Thanks for your help @jjhelmus !!!

**Comment by jjhelmus** [comment]
Needs a build number bump

**Comment by mariusvniekerk** [comment]
yep

**Comment by hmaarrfk** [comment]
why, we moved the old ones to broken. can we just assume that nobody downloaded them?

**Comment by jjhelmus** [comment]
Were the old aarch64 builds removed from anaconda.org?  If so I'll revert the build number bump.

**Comment by hmaarrfk** [comment]
yeah, I had asked @mariusvniekerk to do it on gitter

This is the only one I find that has aarch64:
image

**Comment by jjhelmus** [comment]
Great, I'll revert that commit.

**Comment by hmaarrfk** [comment]
Thanks guys!

**Pull request merged**
