### PR TITLE
ENH add new sysroot for 3.7

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by beckermr** [comment]
cc @xhochy

**Comment by beckermr** [comment]
The errors here are really confusing. Any ideas @isuruf @jjhelmus?

**Comment by beckermr** [comment]
Thanks!

**Comment by xhochy** [comment]
Failure is due to https://github.com/conda-forge/clang-compiler-activation-feedstock/issues/23, will restart in 1h.

**Comment by xhochy** [comment]
@conda-forge-admin please restart ci

**Comment by xhochy** [comment]
@conda-forge/python This is ready for review/merge.

**Comment by beckermr** [comment]
Thanks @xhochy !

**Pull request merged**
