### PR TITLE
Remove unnecessary patches

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
@mingwandroid now that https://github.com/conda-forge/lief-feedstock/pull/12 is merged this patch is unnecessary

**Comment by mingwandroid** [comment]
For patch 0026, I believe that this issue will crop up in other extension modules built with pybind11 on Windows and rather than removing the patch I'd prefer that we reverse the sense of it so that it does nothing by default, but can be activated by setting `CONDA_DLL_SEARCH_MODIFICATION_DO_NOT_DROP_GIL=yes` instead. So it would turn into a debugging tool for us only (and an emergency workaround for people). Your thoughts are very welcome @isuruf.

**Comment by isuruf** [comment]
Sounds good. I'll send a PR if I find time

**Comment by mingwandroid** [comment]
I don't mind if you proceed, then next time I sync back (hopefully soon), I can do this work, but more than happy to share that load with you too, I guess we'll see who gets there first.

**Pull request closed without merging**
