### PR TITLE
Update to 3.8.16

### PR DESCRIPTION
**Pull request by moreshiny**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

### CODE REVIEW

**Comment by moreshiny** [comment]
@conda-forge-admin, please rerender

**Comment by moreshiny** [comment]
CI failure is from setuptools downstream test

`Testing downstream package: setuptools
INFO:conda_build.build:Testing downstream package: setuptools
Reloading output folder: /home/conda/feedstock_root/build_artifacts
TEST START: /home/conda/feedstock_root/build_artifacts/linux-64/setuptools-65.6.3-pyhd8ed1ab_0.tar.bz2
Traceback (most recent call last):
  File "/opt/conda/bin/conda-mambabuild", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/boa/cli/mambabuild.py", line 256, in main
    call_conda_build(action, config)
  File "/opt/conda/lib/python3.10/site-packages/boa/cli/mambabuild.py", line 228, in call_conda_build
    result = api.build(
  File "/opt/conda/lib/python3.10/site-packages/conda_build/api.py", line 180, in build
    return build_tree(
  File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3149, in build_tree
    test(list(local_file.values())[0][0],
  File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2874, in test
    actions = environ.get_install_actions(metadata.config.test_prefix,
  File "/opt/conda/lib/python3.10/site-packages/boa/cli/mambabuild.py", line 124, in mamba_get_install_actions
    solver = _get_solver(channel_urls, subdir, output_folder)
  File "/opt/conda/lib/python3.10/site-packages/boa/cli/mambabuild.py", line 102, in _get_solver
    solver = MambaSolver(channel_urls, subdir, output_folder)
  File "/opt/conda/lib/python3.10/site-packages/boa/core/solver.py", line 127, in __init__
    self.index = load_channels(
  File "/opt/conda/lib/python3.10/site-packages/mamba/utils.py", line 178, in load_channels
    repo = subdir.create_repo(pool)
RuntimeError: Could not read JSON repodata file (/home/conda/feedstock_root/build_artifacts/pkg_cache/cache/cf8a841c.json) parse error line 23: subdir mismatch`

There was no test failure  when this ran in December before s`etuptools` [update](https://github.com/conda-forge/setuptools-feedstock/pull/297) to `65.6.3.` I'll try to look into it but does anyone have a guess what might cause something like this?

**Comment by wolfv** [comment]
Hi @moreshiny thanks for your work here!

I've debugged the same issue recently for another mamba user and it turned out that they had a repodata.json for linux-64 that contained a `noarch` packages. E.g. the repodata for `linux-64/repodata.json` contained a package that specified `"mypkg": { ..., "subdir": "noarch", ... }`

So I suspect that this is a similar issue although I am not sure why that would happen! Could be a conda-build or conda-index issue ...

**Comment by wolfv** [comment]
Hmm, I tried to quickly reproduce it in a codespace but could not so far. I'll try to debug more tomorrow, sorry!

**Comment by moreshiny** [comment]
I saw that 3.11.1 ran through. I'll re-run this one sometime tomorrow to see if this was just a temporary issue.

**Comment by moreshiny** [comment]
No luck, same error. Only 3.7. and 3.11 are not affected. I'll try to find some time to look into it more.

**Comment by wolfv** [comment]
I don't know why, but it seems that the downstream test downloads the package to the `linux-64` subdir folder, even though the package is `noarch`.

I can try to make a simpler reproducer ...

**Comment by jakirkham** [comment]
Moving `setuptools` to `noarch: python` occurred in PR ( https://github.com/conda-forge/setuptools-feedstock/pull/288 ) as part of version `65.3.0` build number `1`. Quite a bit before `setuptools` version `65.6.3` ( https://github.com/conda-forge/setuptools-feedstock/pull/297 ). Did previous `setuptools` packages have issues? Or was it just this one?

**Comment by mattip** [comment]
Somehow PyPy 3.8.16 passed this hurdle and is now available. This means that the resolver will now prefer PyPy over CPython, which is a bad outcome. See [this comment](https://github.com/conda-forge/pypy-meta-feedstock/pull/24#issuecomment-1411884498). Some immediate action is needed before too many people see the problem...

**Comment by mattip** [comment]
@conda-forge-admin please rerender

**Comment by mattip** [comment]
Rerendering seems to have cleared the error. CI is passing.

**Pull request merged**
