### PR TITLE
Update to 3.9.16

### PR DESCRIPTION
**Pull request by moreshiny**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

### CODE REVIEW

**Comment by moreshiny** [comment]
@conda-forge-admin, please rerender

**Comment by moreshiny** [comment]
Same setuptools test failure as #610

**Comment by isuruf** [comment]
cc @wolfv

**Comment by wolfv** [comment]
That Sounds like a noarch Package in the Linux-64 subdir. Ill check in a bit

**Comment by mattip** [comment]
Now #610 is passing but this PR [is failing]() with the setuptools error from #610
```
RuntimeError: Could not read JSON repodata file 
    (/home/conda/feedstock_root/build_artifacts/pkg_cache/cache/cf8a841c.json)
    parse error line 90: subdir mismatch
```

**Comment by moreshiny** [comment]
> Now #610 is passing but this PR is failing with the setuptools error from #610
> 
> ```
> RuntimeError: Could not read JSON repodata file 
>     (/home/conda/feedstock_root/build_artifacts/pkg_cache/cache/cf8a841c.json)
>     parse error line 90: subdir mismatch
> ```

I think #610 only passed because the setuptools test was disabled in https://github.com/conda-forge/python-feedstock/pull/618 and not yet re-enabled with https://github.com/conda-forge/python-feedstock/pull/619

If that's the way to go I can do the same on this one and https://github.com/conda-forge/python-feedstock/pull/614

**Comment by mattip** [comment]
I am only tangentially involved, but that seems to make sense to move this forward.

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Pull request merged**
