### PR TITLE
3.7.8

### PR DESCRIPTION
**Pull request by jjhelmus**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jjhelmus** [comment]
@conda-forge-admin, please rerender

**Comment by jjhelmus** [comment]
@conda-forge-admin, please rerender

**Comment by jjhelmus** [comment]
This is passing CI but I would like to resolve the question no where `cpython` should appear in the build string (at the end or beginning) prior to merging this.  @isuru and @mbargull seem most interested in this.

**Comment by mbargull** [comment]
@isuruf (missing "f" above ;).)

Yes, please return to the `h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_cpython` scheme -- then we don't have to change anything downstream in `conda-forge-pinning` etc. :).

----
I also did a quick review: Apart from the build string, this looks alright to me (not know if anything else changed in CPython).
But man, viewing `diff`s of `diff`s really does not have the nicest highlighting on GitHub!

**Comment by jjhelmus** [comment]
I've moved `cpython` to the end of the build string.

Usually the patch diffs are cleaner and easier to review, for example in #358.  I think the refresh here included a change in line endings which causes the who file to get highlighted.

**Comment by mbargull** [comment]
> I think the refresh here included a change in line endings which causes the who file to get highlighted.

Ah right. Would be good if it highlighted carriage returns (at least when they are added/removed)...
When Ray updates things again, we'd have the same situation once more in the opposite direction then, I guess.

**Pull request merged**
