### PR TITLE
Update to 3.11.1

### PR DESCRIPTION
**Pull request by moreshiny**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

I had to refactor `recipe/patches/0017-Make-dyld-search-work-with-SYSTEM_VERSION_COMPAT-1.patch` as the surrounding code changed a bit. @isuruf it would be good if you double check this still does what you intended.

Closes https://github.com/conda-forge/python-feedstock/pull/612

### CODE REVIEW

**Comment by moreshiny** [comment]
@conda-forge-admin, please rerender

**Comment by mattip** [comment]
CI is passing.

**Comment by isuruf** [comment]
Can you merge https://github.com/conda-forge/python-feedstock/pull/602 into this PR?

**Comment by moreshiny** [comment]
> Can you merge #602 into this PR?

patch fix from #602 now included

**Comment by Syrus** [comment]
I love conda-forge, but we are falling pretty far behind on this one.

**Comment by jakirkham** [comment]
Should we update to 3.11.2?

**Comment by ocefpaf** [comment]
> Should we update to 3.11.2?

For "historic" reasons I'd like to have this one merged if folks are OK with it and submit a new PR for 3.11.2.

**Comment by beckermr** [comment]
LGTM!

**Comment by isuruf** [comment]
windows builds seem to be skipped here and osx builds are failing.

**Comment by jakirkham** [comment]
[The failure]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=679185&view=logs&j=f23f984a-2b8a-59f7-ed33-e22fa8dd9908&t=1d351711-1535-5fad-3bab-ff535f39fb55&l=16828 ) doesn't look like a package issue, but instead some sort of Conda/Conda-Build/Mamba issue

```
RuntimeError: Could not read JSON repodata file (/Users/runner/miniforge3/pkgs/cache/54fe620e.json) parse error line 84: subdir mismatch
```

Going to try restarting those jobs

**Comment by jakirkham** [comment]
Regarding Windows, is it possible this `skip` is causing issues (taken from `main`)?

https://github.com/conda-forge/python-feedstock/blob/21038d707640da7b5da152a5239e199c720f0574/recipe/meta.yaml#L84-L86

**Pull request closed without merging**
