### PR TITLE
Rerender the feedstock

### PR DESCRIPTION
**Pull request by jjhelmus**
closes #11

### CODE REVIEW

**Comment by jjhelmus** [comment]
See #11 for a work on debugging this issue and an explanation of the fix.

**Comment by jjhelmus** [comment]
I don't think AppVeyor actually needs quotes, apparently conda 4.1.0 broke something in the test phase that was working in 4.0.8

**Comment by jakirkham** [comment]
Looks like you might be right. Going to try to reproduce it in another case just to be sure.

**Comment by jjhelmus** [comment]
Going to leave this be for a bit until the conda issue gets worked out.

**Comment by jjhelmus** [comment]
So all the builds are good, is this worth merging so that the win-64 builds goes out or should we wait until a conda 4.1.1 release is made and the order of adding and list channels is no longer needed?

**Comment by msarahan** [comment]
Thanks for figuring this mess out.

**Pull request merged**
