### PR TITLE
Fix ffi issue

### LINKED ISSUE #522: Python 3.10.0 crashes on MacOS x86_64
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue: Two conda-forge repos having strange crashes within CI on MacOS with python 3.10.0

Note: I am not a mac user, but am just attempting to help conda-forge repos get green CI builds :)

Examples of CI crashes: conda-forge/magics-feedstock#106 and conda-forge/shapely-feedstock#92

I do have an old mac that I am able to reproduce the shapely crashes and have gotten some iterative feedback here along with `lldb` output:  Toblerity/Shapely#1227

Does anybody here have interest / mac experience to help figure out what is wrong?  Thanks!

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Fixes #522
Closes #523
Closes #524

### CODE REVIEW

**Review by jakirkham — APPROVED** [review]

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by h-vetinari** [comment]
One of the travis builds for this failed after merging - could someone restart it?

**Comment by h-vetinari** [comment]
Thanks for restarting!

Also: awesome work by lots of people in terms of connecting many different dots. 🥳

**Comment by mbargull** [comment]
> Also: awesome work by lots of people in terms of connecting many different dots. partying_face

Very much agreed! Thanks to everyone involved for digging up everything to get to the button and fixing this!

**Pull request merged**
