### PR TITLE
Python v3.9.11

### PR DESCRIPTION
**Pull request by jnooree**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jnooree** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
Hi @jnooree, could you please follow the instructions here to update the patches? This may be all you need to fix this.

https://github.com/conda-forge/python-feedstock/blob/main/recipe/patches/README.md

**Comment by jnooree** [comment]
Regenerated! How about including this step in the CI?

**Comment by ngam** [comment]
Get this patch from my PR: [083bb33](https://github.com/conda-forge/python-feedstock/pull/558/commits/083bb3306cea6824b7e152dd2b8b1799e6b218d0) or generate it from this PR https://github.com/python/cpython/pull/31974

Or we can wait for 3.9.12 and 3.10.4 which have just been released...

**Comment by jnooree** [comment]
Oh.. I'll close this and reopen for 3.9.12. Thanks for information.

**Comment by ngam** [comment]
> Oh.. I'll close this and reopen for 3.9.12. Thanks for information.

No problem, but I am not really sure what's going on. Someone rom the maintainers will have to approve this. Follow the convo in the other PR to see what they decide...

**Comment by ngam** [comment]
The good news they also released a tag for 3.9.12, so you could do it right away, remember to regen the patches :)

https://github.com/python/cpython/commit/b28265d7e6a41a4a0e227b37f4fbbc4d03a0a707

**Pull request closed without merging**
