### PR TITLE
v3.9.13

### PR DESCRIPTION
**Pull request by ngam**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
@conda-forge/python could someone look at this windows failure? looks weird and unrelated. Everything else is ready to go.

**Comment by ngam** [comment]
update: windows error can be traced to this commit: https://github.com/conda/conda/commit/b19fae858fdb28841b646e6179f42b7691441b1a

**Comment by ngam** [comment]
Fixed in https://github.com/conda/conda-build/pull/4482

**Comment by ngam** [comment]
Someone restarted the build behind my back 😂 that's a good sign

**Comment by isuruf** [comment]
Thanks

**Pull request merged**
