### PR TITLE
Provide Python 3.8.0b1

### PR DESCRIPTION
**Pull request by h-vetinari**
Next step for #254, following the work of @jjhelmus in #258 and my (still failing attempt in #259).

If someone is annoyed at me mucking around with this, just let me know.

Tried the rebasing-workflow recommended by @mingwandroid in #259, and it works much better, but I'm not sure I managed to avoid corruption of some line endings (working on windows; but conda-build can apply the patches without problems).

### CODE REVIEW

**Comment by h-vetinari** [comment]
Ah, damn, I forgot to change the target branch to `3.8`... could one of you do that for me please?

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
Due to the re-render error (already from #259), I re-rendered locally, and didn't have an issue. Not sure why the bot is unhappy.

**Comment by h-vetinari** [comment]
Ok, have to stop this now, I've already sacrificed most of my sleep... Can't figure out how to get the line endings to behave again. I can `conda build` locally and it works, but I've tried a couple ways with line-endings (incl. the one with the least diff; LF for git-lines, CRLF for others in patches 11/17/18), and on the server it doesn't... oh well.

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
So, after improving my crlf-fu a bit, at least the patches go through now. It seems to me that the various `python{VER}m` files ending in an "m" are not built anymore, so I removed something from `build.sh` had stumped me already in #259.

The windows failure is the same as in #258, where @jjhelmus [commented](https://github.com/conda-forge/python-feedstock/pull/258#issuecomment-485583191) that this is not an issue (assuming the rest now passes).

**Comment by h-vetinari** [comment]
@conda-forge/python I'm currently a bit stuck with the remaining ffi/openssl errors. Anyone care to take a look?

**Comment by scopatz** [comment]
It just looks like some include paths are bad on windows

**Comment by h-vetinari** [comment]
@scopatz 
Thanks for taking a look! Do you know where can I adjust those include paths? There's nothing I can see in `meta.yaml`

I just noticed now that libffi is actually a host/run dependency for `[not win]`, but I had experimented already before to use the libffi from conda-forge and that ended up not being found either.

**Comment by scopatz** [comment]
Probably in the build.bat file?

**Comment by jjhelmus** [comment]
Can this be rebased are targeted at the `pre-3.8` branch?

**Comment by h-vetinari** [comment]
> @jjhelmus: Can this be rebased are targeted at the `pre-3.8` branch?

Absolutely! I already [asked](https://github.com/conda-forge/python-feedstock/pull/261#issuecomment-499305652) further up if someone can switch it for me, as I don't have the permissions to change the target branch.

**Comment by jjhelmus** [comment]
Sorry I missed your earlier comment.  I switched the target branch.

**Comment by h-vetinari** [comment]
> @scopatz: Probably in the build.bat file?

If I understand correctly, there would need to be a build-vsproj in `PCbuild` for `libffi`? That sounds above my capabilities right now. How can I link to the conda-forge libffi from `bld.bat`? Since you've joined just now, do you maybe have any pointers, @jjhelmus?

**Comment by scopatz** [comment]
Maybe you can rebase to that branch?

**Comment by h-vetinari** [comment]
> @scopatz: Maybe you can rebase to that branch?

It is already based on that branch, I had just forgotten to change the target branch when I opened the PR (otherwise there would now be merge conflicts).

**Comment by h-vetinari** [comment]
@conda-forge/core @condaf-forge/python
This PR would allow lots of projects easy access to advance to testing python 3.8. I've tried and failed with #259, and can't really see myself succeeding with the libffi-stuff here.

Python 3.8b2 is around the corner, and packaging it would presumably be easier based on the work done here. As I'll be away for two weeks starting Monday, I just wanted to make it explicit that anyone wanting to help with this up is free to commit into this PR or continue based on this in a separate PR.

**Comment by scopatz** [comment]
thanks! Hopefully someone can pick this up

**Comment by h-vetinari** [comment]
Closing as superseded by #268 / #271.

**Pull request closed without merging**
