### PR TITLE
Python 2.6.9

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/conda-forge/python-feedstock/issues/5

Attempts to build Python 2.6.9 mainly for historic value and people wishing to use it in CIs.

Note: This pulls in the history from 2.7.x as it shares more in common with the 2.6.9 build.

### CODE REVIEW

**Comment by jakirkham** [comment]
The Windows failure appears related to a function called `find_best_ssl_dir` in `PCbuild/build_ssl.py`. FWR it is being given `..\\..` as the place to look for a directory that has filenames that start with `openssl-`. Not entirely sure why this was done in this manner. However, it will either need to be patched or overridden with some kind of option.

**Comment by jakirkham** [comment]
I know this may not be the most interesting thing going on at conda-forge right now, but we do you think about this @jjhelmus? Right now Windows is bust, but I could skip it for now and we could have Mac and Linux packages.

**Comment by jjhelmus** [comment]
Sorry been a bit busy the last few weeks @jakirkham.  I see some use for a Python 2.6 `conda-forge` release (`defaults` has one as well) but don't have the time to investigate the Windows issue at the moment.  I would be fine merging this with the Windows build skipped to get out Linux and MacOS packages.

**Comment by jakirkham** [comment]
Thanks @jjhelmus. Have disabled Windows.

Do you know what we ended up deciding with `bzip2`, @jjhelmus? I remember discussing that we were using the static library before, but now we have issues as a dynamic library is also included in the `bzip2` package. This seems to be causing the failure on Linux. Not sure how macOS avoids it as it appears to be [linked]( https://travis-ci.org/conda-forge/python-feedstock/builds/224361142#L4969 ) to the same `libbz2` dynamic library.

**Comment by jjhelmus** [comment]
There are likely two options for the bzip2 issue:

1. Link to the dynamic library and include bzip2 in the run requirements.
2. Delete the dynamic bzip2 library prior to the build so that the `bz2` module is linked statically.

There may be some issues with 1 if the bzip2 package is every updated in an environment as I believe conda uses the `bz2` module to unpack the package prior to linking.  Removing a dynamic library being used by a running process is a great way to cause a bus error.  So 2 is probably the safer option.  There is likely some compiler/linked switch that will force the bzip2 library to be statically linked but I think removing the dynamic library would require less work.

**Comment by jakirkham** [comment]
Perfectly fine with deleting the bzip2 dylib/so as part of the build script. Have pushed a fix along those lines to this branch. If it works, we can port it to the other Python branches as well.

**Comment by jakirkham** [comment]
Took some tweaking, but this seems to be doing the right thing now. What do you think?

**Comment by jjhelmus** [comment]
LGTM, thanks for putting this together @jakirkham

**Pull request merged**
