### PR TITLE
Updating to Python 3.6 release version.

### PR DESCRIPTION
**Pull request by Nelthorim**
Not sure if I need to do something else (not used to the format of conda recipes). Maybe merge to master afterwards, as this is a release version?

### CODE REVIEW

**Comment by jakirkham** [comment]
We should move this to `master` as it is not a prerelease.

**Comment by Nelthorim** [comment]
I agree. I changed the push branch to `master`. However, I cannot resolve the conflicts easily in the Github web UI due to isaacs/github#839. I can check how to it in the command line tomorrow or somebody with write permission could do it for me. (Sorry if this is sloppy for my first PR.)

**Comment by ericmjl** [comment]
Can't wait to see Python 3.6 in conda-forge! Thanks you guys for maintaining it! :smile:

**Comment by Nelthorim** [comment]
I think that should do it. Please come back to me if I messed up somewhere, this has been an interesting learning experience 😄

**Comment by jakirkham** [comment]
It might just be easier to do a fresh PR.

**Pull request closed without merging**
