### PR TITLE
Rerender the 3.6 branch to use clang 9

### PR DESCRIPTION
**Pull request by jschueller**
@conda-forge-admin, please rerender

rerendering should use clang 9 on osx and fix:
https://github.com/conda-forge/pyside2-feedstock/issues/46

### CODE REVIEW

**Comment by jschueller** [comment]
does anyone know how to deal with this error ?
```
PCbuild\pythoncore.vcxproj(42,3): error MSB4019: The imported project "D:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
 ```

**Comment by jschueller** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
`undef: ___llvm_profile_runtime` is because of an issue in our `compiler-rt` package which was fixed recently.

**Comment by jschueller** [comment]
@isuruf now on windows I get:
```pythoncore.vcxproj(42,3): error MSB4019: The imported project "D:\Microsoft.Cpp.Default.props" was not found.```

**Comment by jschueller** [comment]
@isuruf it seems to go much further on appveyor, unfortunately it timeouts

**Comment by mariusvniekerk** [comment]
You can try building with vs2017

**Pull request merged**
