### PR TITLE
WIP: Python 2.7.12

### LINKED ISSUE #2: Python 2.7
Would be nice to build Python 2.7.  

[Source code for Python 2.7.11](https://www.python.org/downloads/release/python-2711/)

[anaconda-recipes python-2.7 recipe](https://github.com/ContinuumIO/anaconda-recipes/tree/8e3e7c10c929659e5c7c06a3204a5c081efbfe4c/python-2.7)

### PR DESCRIPTION
**Pull request by jjhelmus**
closes #2

### CODE REVIEW

**Comment by jjhelmus** [comment]
Marking as WIP as I want to check the contents of the Windows package against the package in `defaults`.  

That said, please review and provide any feedback as if this was ready.

**Comment by jakirkham** [comment]
I'm guessing we are going to backport similar fixes as seen in PR ( https://github.com/conda-forge/python-feedstock/pull/51 ), correct?

**Comment by jjhelmus** [comment]
> I'm guessing we are going to backport similar fixes as seen in PR ( #51 ), correct?

Yes, I think I've applied most of them.  [`anaconda-recipes`](https://github.com/ContinuumIO/anaconda-recipes/blob/master/python-2.7/meta.yaml) has a few additional patches that are applied but from what I can tell they are not needed.

* version.patch : No needed, we use the `brand_python` script to add text to the version text
* site.patch : No idea what this is doing but seems to be anaconda specific
* cprt.patch : more changed required for the version string
* linux-clear_history.patch : Maybe something funny with readline, want to test locally
* fix-readline-extra-space.patch : Ditto
* osx-site.patch : Not sure on this one
* win-cygwin.patch : Not sure on this one

**Comment by jakirkham** [comment]
> cprt.patch : more changed required for the version string

Seems more like some kind of [info]( https://github.com/ContinuumIO/anaconda-recipes/blob/dc416e62b964fe1a8a9aadcd95c8b3e53a5b63d8/python-2.7/cprt.patch#L13-L14 ). In any event, I agree we don't need it.

> linux-clear_history.patch : Maybe something funny with readline, want to test locally

Ugh. Yeah, I agree. Let me know if I can help.

> fix-readline-extra-space.patch : Ditto

This looks like some build changes for OS X. Maybe changing the search path or something. I'm not sure if we need it or not.

> osx-site.patch : Not sure on this one

It looks like this is handling the case of `python.app`. Not sure either though.

> win-cygwin.patch : Not sure on this one

Looks like they are parameterizing Cygwin builds somehow. No clue though. Someone else should weigh in.

**Comment by jakirkham** [comment]
This appears to be pointed at `master`. Should we get a `2.7` branch going and PR it to that?

**Comment by jjhelmus** [comment]
> This appears to be pointed at master

Just say this too.  I have a build that I created locally that I want compare the contents vs the version in `defaults`.  Will submit a PR against a `2.7` branch a bit later tonight.

**Comment by jjhelmus** [comment]
Found a few changes that are needed in the windows build, taking a bit longer than I expected to fix.  Probably will wait till tomorrow to submit this against a new branch and finish things off.

**Comment by jjhelmus** [comment]
closed in favor of #62.

**Pull request closed without merging**
