### PR TITLE
Apply bzip2 shared library fix and rerender recipe

### PR DESCRIPTION
**Pull request by jjhelmus**

### CODE REVIEW

**Comment by jjhelmus** [comment]
closing in favor of #140

**Comment by jakirkham** [comment]
Guessing we need to borrow commit ( https://github.com/conda-forge/python-feedstock/commit/ebc038014f89a2d2c7a566707be4770bc4a5c9d6 ).

**Comment by jjhelmus** [comment]
This could use a review.

**Comment by jakirkham** [comment]
Thanks @jjhelmus.

**Pull request merged**
