### PR TITLE
Use latest SDK to build

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by isuruf** [comment]
@conda-forge/python, this is ready for review. `3.9.1.rc1` supports building with a new SDK and using an older `MACOSX_DEPLOYMENT_TARGET`

**Comment by mbargull** [comment]
ref: https://github.com/python/cpython/pull/23295

@isuruf, are there any additional post-build tests we should/could add?

**Comment by isuruf** [comment]
I don't think so

**Comment by isuruf** [comment]
Ready now

**Comment by mbargull** [comment]
Is it worthwhile to enable artifacts on Azure on this feedstock to let someone inspect used symbols, akin to https://github.com/conda-forge/python-feedstock/pull/371#issuecomment-681073286 ?
(Sorry for these banal questions; I'm just trying to be cautious whilst not knowing much about Macs.)

**Comment by isuruf** [comment]
I can test on a 10.9 machine after this is merged. It's on `python_rc` label anyway.

**Comment by isuruf** [comment]
Going to merge to `python_rc` label and test

**Pull request merged**
