### PR TITLE
Update to 3.8.1

### PR DESCRIPTION
**Pull request by mingwandroid**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mingwandroid** [comment]
This should be ready now. No luck with PGO still I guess?

**Comment by mingwandroid** [comment]
One question, do we want to use `--pgo` or `--pgo-extended` on Unix?

For discussion see: https://docs.python.org/3/whatsnew/changelog.html#id48
and: https://bugs.python.org/issue36044

**Comment by mariusvniekerk** [comment]
I think given the arguments in that discussion I'm happy for just using pgo instead of the extended ones.

**Comment by scopatz** [comment]
Yes, me too.

**Comment by mingwandroid** [comment]
Thanks for the merge! My next PR to this feedstock will add the ability to make debuggable builds of Python, I hope.

**Pull request merged**
