### PR TITLE
Build Python 3.6.6 using separate patches and build script for the compiler variants 

### PR DESCRIPTION
**Pull request by jjhelmus**
This splits the `toolchain` and `gcc/clang` builds with a separate set of patches and build script used for each.  The `toolchain` build closes matches the build as of PR #188.  The `gcc/clang` builds mirror AnacondaRecipes.  

I think this will be a more maintainable setup for this recipe until the compiler migration is complete at which time the `toolchain` patches and build script can be removed.

The downside of this is that the `toolchain` python package no longer has PGO .

### CODE REVIEW

**Comment by jjhelmus** [comment]
I'd appreciate a review on this approach (perhaps @ocefpaf or @mingwandroid ).  It is a big change but seem to me to be a safe approach to insure a reliable `toolchain` based build while the compiler migration is in progress.

**Comment by mariusvniekerk** [comment]
Do we need a similar one for py37?

**Comment by ocefpaf** [comment]
> I'd appreciate a review on this approach (perhaps @ocefpaf or @mingwandroid ).

IMO everything looks OK but I'm really not the person to review this :smile:

I trust @mingwandroid and @mariusvniekerk expertise there to merge this one. Thanks @jjhelmus for putting this together!

**Comment by mingwandroid** [comment]
All checks passed, and more tests added, let's roll. Thanks @jjhelmus for taking up the baton.

**Comment by mingwandroid** [comment]
(btw I have no merge rights for this feedstock)

**Comment by ocefpaf** [comment]
> (btw I have no merge rights for this feedstock)

You should though :-/

See https://github.com/conda-forge/python-feedstock/pull/212/files#diff-e178b687b10a71a3348107ae3154e44cR160

**Comment by ocefpaf** [comment]
@mariusvniekerk we are building the old toolchain on CircleCI here too. What was the final decision on that? Or do we expected the lib mismatch to re-appear?

**Comment by jjhelmus** [comment]
> Do we need a similar one for py37?

I think so, I'll check and put together a PR if it is needed this weekend.

**Pull request merged**
