### PR TITLE
Various Python 3.4 fixes

### PR DESCRIPTION
**Pull request by jjhelmus**
Makes python 3.4 recipe similar to recipe in anaconda-recipes

### CODE REVIEW

**Comment by jjhelmus** [comment]
This work is similar to the changed made for Python 3.5 in #51

**Comment by jjhelmus** [comment]
Any comments? I want to get this merged so that the new version can be tested to see if it fixes the issue in #49.

**Comment by jakirkham** [comment]
LGTM. As stated before, not sure I'm qualified to comment on Windows.

**Comment by msarahan** [comment]
Thanks @jjhelmus

**Pull request merged**
