### PR TITLE
ENH add new sysroot name for 3.6

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by beckermr** [comment]
cc @isuruf

**Comment by isuruf** [comment]
How can we make sure that only the new compilers are used with this?

**Comment by beckermr** [comment]
At build or runtime?

**Comment by isuruf** [comment]
runtime

**Comment by beckermr** [comment]
We can mark the builds of ld on the 2.34 branch as broken. I think we have enough symlinks in other places to ensure this will work.

**Comment by beckermr** [comment]
Ohhh you mean for python C extensions? We can insert run_constrained bits that pick out out the new compilers via their versions (marking the older 7.5.0 ones as broken).

**Comment by jjhelmus** [comment]
Rather than replacing the existing `_sysconfig...` files, can we include additional files for the new sysroot name? That is to say, include copies for both sysroot names.  I believe with both, it should be possible to build Python extensions with both the new and older compilers.

**Comment by beckermr** [comment]
I didn't think that was possible but I'll give it a try.

**Comment by beckermr** [comment]
Please don't merge yet. I fixed a bug somewhere else and need to remove a hack here.

**Comment by beckermr** [comment]
@isuruf Do we need to mark the builds of binutils 2.34 with the old sysroots as broken as well? They have the right symlinks so probably not, but I am not sure.

**Comment by isuruf** [comment]
No, they have the correct symlinks.

**Comment by beckermr** [comment]
@conda-forge/python @isuruf I think this is ready to merge!

**Comment by jjhelmus** [comment]
LGTM, thanks @beckermr

**Comment by beckermr** [comment]
great - I won't be able to get to 37 or 38 for a few days likely - maybe tonight...

**Comment by xhochy** [comment]
@beckermr Probably https://github.com/conda-forge/python-feedstock/pull/368 would be fixed by your work then?

**Comment by xhochy** [comment]
Issue is that it doesn't have a `_sysconfigdata_x86_64_conda_linux_gnu.py` in `${RECIPE_DIR}/sysconfigdata`. This looks very much like what you are doing here :D

**Comment by beckermr** [comment]
Yep. I won't be able to get to 37 or 38 until Friday.

**Comment by xhochy** [comment]
No worries as long as I know it's not my fault and someone knows a solution, I'm happy.

**Pull request merged**
