### PR TITLE
Update cross-compile osx-arm64 configure vars to match native

### PR DESCRIPTION
**Pull request by erykoff**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

This is the same as #432 for python 3.8.  cc @xhochy

### CODE REVIEW

**Comment by erykoff** [comment]
@isuruf the drone is looking for Linux aarch 64?

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by xhochy** [comment]
This PR was not rebased on the latest 3.8 branch, thus the failures.

**Review by mbargull — CHANGES_REQUESTED** [review]
Build number should be bumped.

**Review by mbargull — APPROVED** [review]

**Comment by mbargull** [comment]
Travis CI has some HTTP issues. I'm merging this anyway. (We can try to restart Travis builds later. Or not; shouldn't matter because ppc64le builds are unaffected by this change either way.)

**Comment by mbargull** [comment]
@conda-forge-admin, rerender

**Pull request merged**
