### PR TITLE
updated v3.10.8

### PR DESCRIPTION
**Pull request by mbargull**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mbargull** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
Interesting not seeing it on [this page]( https://www.python.org/doc/versions/ ). Maybe we should wait a bit?

**Comment by mbargull** [comment]
> Interesting not seeing it on [this page](https://www.python.org/doc/versions/). Maybe we should wait a bit?

IDK, the releases are already 6 weeks old. Seems rather that the /versions page hasn't been updated unintentionally. You may wants to report this at https://github.com/python/pythondotorg or whatever repository is appropriate for that.

**Comment by jakirkham** [comment]
Thanks Marcel! 🙏

**Pull request merged**
