### PR TITLE
Python 1.3

### PR DESCRIPTION
**Pull request by jjhelmus**

### CODE REVIEW

**Comment by jjhelmus** [comment]
Library requirements for python binary on Linux:

```
ldd /opt/conda/pkgs/python-1.3-0/bin/python
	linux-vdso.so.1 =>  (0x00007fffac5e1000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f0dec18f000)
	libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007f0debf57000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f0debd53000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f0deb9bf000)
	libfreebl3.so => /lib64/libfreebl3.so (0x00007f0deb7bb000)
	/lib64/ld-linux-x86-64.so.2 (0x0000562fc8194000)
```

`libcrypt` and `libfreebl` may not be present on all system

**Comment by msarahan** [comment]
What strange history project have you undertaken?

**Comment by jakirkham** [comment]
As before, `libcrypt` is fine to assume it is present as it is part of `glibc`. Same story with `libfreebl3`. Again we should re-render after changing `skip`.

**Comment by jjhelmus** [comment]
> What strange history project have you undertaken?

Something fun over the three day weekend to explore how the Python build system has changed over the years.  Will burn a bit of CI time but should be small.

**Comment by msarahan** [comment]
Cool man.  Not worried about CI time - they'll get there eventually.  Let's not get any strange ideas about being the Wayback Machine for all of python's ecosystem, though. 😉

**Comment by jjhelmus** [comment]
closed in favor for #53 which applied these changes to the `historic` branch.

**Pull request closed without merging**
