### PR TITLE
3.6.10

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
@beckermr, the bot merged this PR before appveyor finished.

**Comment by beckermr** [comment]
Hmmm. Because of the registration issues with appveyor, the bot tries to compute if appveyor is needed and if it is not, then it ignores it. I am guessing I put in buggy logic for that.

**Comment by beckermr** [comment]
Here is the issue. The win provider is marked as azure in this feedstock.

https://github.com/conda-forge/python-feedstock/blob/master/conda-forge.yml#L6

**Comment by isuruf** [comment]
That's on master though. On 3.6 branch https://github.com/conda-forge/python-feedstock/blob/3.6/conda-forge.yml

**Comment by beckermr** [comment]
Ahhhh. The bot is checking the master branch because that is where the task runs. It needs to checkout the target branch. 

TBH, we should be fixing appveyor as opposed to putting in this logic. 

You fixed a bunch of things already, so I think we simply remove this check from the bot and then fix anything else as we go along.

**Pull request merged**
