### PR TITLE
v3.8.8

### PR DESCRIPTION
**Pull request by junpuf**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
~~* [] Bumped the build number (if the version is unchanged)~~
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

#450

### CODE REVIEW

**Comment by junpuf** [comment]
@conda-forge-admin, please rerender

**Comment by junpuf** [comment]
going to reapply patches

**Comment by junpuf** [comment]
```
Applying patch: /home/conda/recipe_root/patches/0017-Unvendor-openssl.patch with args:
['-Np1', '-i', '/tmp/tmpufkcz1fb/0017-Unvendor-openssl.patch.native', '--binary']
checking file PCbuild/_ssl.vcxproj
checking file PCbuild/_ssl.vcxproj.filters
checking file PCbuild/openssl.props
checking file PCbuild/python.props
Hunk #1 FAILED at 62.

```

**Comment by isuruf** [comment]
Thanks

**Pull request merged**
