### PR TITLE
update for 3.8.2

### PR DESCRIPTION
**Pull request by ngoldbaum**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ngoldbaum** [comment]
@conda-forge-admin, please rerender

**Comment by ngoldbaum** [comment]
I don't think I'm going to be very helpful in figuring out any build failures here. If anyone else wants to push to this branch of supercede this PR please feel free.

**Comment by jjhelmus** [comment]
@mingwandroid Was there a patch needed for Python 3.8 to work  LEIF?  If so it would be great if we could get in into Python 3.8.2 to make is easier to specify a compatible version.

**Comment by scopatz** [comment]
@jjhelmus - I think there is another PR open for that

**Comment by jjhelmus** [comment]
> @jjhelmus - I think there is another PR open for that

Yes #314 includes the patch I was thinking about it.  Would be good to pull in into this PR.

**Comment by jjhelmus** [comment]
Builds pass and can be merged as is.  Getting the changes in #315 and `0026-Revert-part-of-https-bugs.python.org-issue33895-http.patch`from #314 in at the same time would be very nice.

**Comment by scopatz** [comment]
I am going to merge, so that we have access to this then

**Pull request merged**
