### PR TITLE
Fix Openssl3 + py37 on windows failure

### PR DESCRIPTION
**Pull request by akrherz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
*  Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Adds a test showing the openssl3 + python3.7 failure.  Will iterate on a patch to then fix this.

Fixes https://github.com/conda-forge/python-feedstock/issues/516

### CODE REVIEW

**Comment by akrherz** [comment]
Great, the failure reproduced only on windows + openssl3
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\bld\python_1634123290171\_test_env\lib\ssl.py", line 589, in create_default_context
    context.load_default_certs(purpose)
  File "D:\bld\python_1634123290171\_test_env\lib\ssl.py", line 490, in load_default_certs
    self._load_windows_store_certs(storename, purpose)
  File "D:\bld\python_1634123290171\_test_env\lib\ssl.py", line 482, in _load_windows_store_certs
    self.load_verify_locations(cadata=certs)
ssl.SSLError: unknown error (_ssl.c:4034)
```

Patch iteration coming in a bit

**Comment by akrherz** [comment]
OK, this should be ready to go.  My understanding of why this patch fixes the issue is that the ASN1 reader was incorrectly erroring when it found an unexpected EOF on the `bytearray`, but it should have been OK.  This code path is unique to windows.

**Comment by jakirkham** [comment]
Woot! 🎉 Thanks @akrherz! 😄 

Would it make sense to add the `urlopen` example from issue ( https://github.com/conda-forge/python-feedstock/issues/516 ) as a test as well?

**Comment by akrherz** [comment]
> Would it make sense to add the `urlopen` example from issue ( #516 ) as a test as well?

I don't believe so as that would introduce a network availability requirement for the test to succeed.  I added a test that exercises the same failing codepath.

**Pull request merged**
