### PR TITLE
Fixes for Windows GCC interop needed by RPy2 and (potentially) CVXOPT

### PR DESCRIPTION
**Pull request by mingwandroid**
Here you go @ocefpaf

### CODE REVIEW

**Comment by mingwandroid** [comment]
OK, done:

https://github.com/conda-forge/python-feedstock/pull/142 and https://github.com/conda-forge/python-feedstock/pull/143

**Comment by ocefpaf** [comment]
Thanks @mingwandroid!

**Comment by jjhelmus** [comment]
Thanks for this @mingwandroid. Is there a reason for replicating the patch files in the root directory and the recipe directory?  Also should these patches be applied on all platforms or just Windows?

**Comment by mingwandroid** [comment]
I have a problem with the idea of patching on only some platforms. That means that your patch is possibly not upstreamable because it may break other platforms. Patches should never break other platforms and if they do they need to be reworked until they don't.

If you were to attempt to cross compile Python modules on Linux using mingw-w64 GCC then this patch would be necessary there too.

**Comment by mingwandroid** [comment]
They shouldn't be in the root, I'll force push in a mo.

**Comment by jjhelmus** [comment]
LGTM, will merge once the CI are green.  Thanks @mingwandroid

**Comment by mingwandroid** [comment]
Oh I have another fix incoming.

**Pull request merged**
