### PR TITLE
Update to 3.10.11

### PR DESCRIPTION
**Pull request by jakirkham**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render

**Comment by jakirkham** [comment]
Patches needed a rebase. Could someone please review?

**Comment by drewgilliam** [comment]
@conda-forge/python - any chance of this PR for python 3.10.11 being merged soon?  Thanks!

**Comment by jakirkham** [comment]
Going ahead and merging. If there are issues, we can follow up

**Pull request merged**
