### PR TITLE
Skip osx toolchain

### PR DESCRIPTION
**Pull request by ocefpaf**
I had to pull the OS X packages generated from #212 b/c we are now building OS X on CircleCI instead of Travis-CI and that breaks backward compatibility.

Because the old Python package created with Travis-CI is OK let's just skip it here to avoid breaking the ecosystem every time we need a rebuild.

### CODE REVIEW

**Comment by mariusvniekerk** [comment]
LGTM

**Comment by jjhelmus** [comment]
Does this means that if a bug is found in the `toolchain` build for osx we have no method of releasing a fixed version?

**Comment by ocefpaf** [comment]
> Does this means that if a bug is found in the toolchain build for osx we have no method of releasing a fixed version?

Yep. Exactly. Unless someone with more time create a branch and revert the patches that prevent the build from happening on Travis-CI :smile:

Paraphrasing myself here when @mariusvniekerk and I decided to do this: keep the toolchain on life support sucks :stuck_out_tongue_winking_eye:

**Comment by jakirkham** [comment]
That or we can create branches for the `toolchain` build starting from when it last worked.

**Pull request merged**
