### PR TITLE
Python 3.11.0a3

### PR DESCRIPTION
**Pull request by xhochy**
I would like to build the alpha releases from time to time as I hope this will make the work for us easier once the release (candidates) come out. 

Also, I did comment out the downstream tests, is there a better solution?

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
```
2>dynload_win.obj : error LNK2001: unresolved external symbol _CondaEcosystemModifyDllSearchPath [D:\bld\python-split_1640193704982\work\PCbuild\_freeze_module.vcxproj]
     2>pylifecycle.obj : error LNK2001: unresolved external symbol _CondaEcosystemModifyDllSearchPath_Init [D:\bld\python-split_1640193704982\work\PCbuild\_freeze_module.vcxproj]
     2>D:\bld\python-split_1640193704982\work\PCbuild\win32\_freeze_module.exe : fatal error LNK1120: 2 unresolved externals [D:\bld\python-split_1640193704982\work\PCbuild\_freeze_module.vcxproj]
```

**Comment by h-vetinari** [comment]
3.11.0beta1 has now been released - is it perhaps time to respin this PR?

**Comment by xhochy** [comment]
Happy to continue to work on this, my main issue is to fix the line endings in `recipe/patches/0014-Add-CondaEcosystemModifyDllSearchPath.patch`. Otherwise, this should be building. The line endings freaked me out though.

**Comment by isuruf** [comment]
We should get rid of CONDA_DLL_SEARCH_MODIFICATION_ENABLE=1 mode entirely anyways. I'll have a look in refreshing that patch.

**Comment by isuruf** [comment]
Closing in favour of #577

**Pull request closed without merging**
