### PR TITLE
v3.10.5

### PR DESCRIPTION
**Pull request by ngam**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ngam** [comment]
Will close this in case someone else wants to submit a different PR but they stop because they think there is a blocker.

**Comment by ngam** [comment]
@isuruf, do you want me to attempt dealing with this? I believe we had a similar problem with the singularity feedstock once and @chrisburr added this line:

```bash
# Workaround for travis permissions errors which end up creating very verbose log output
if [[ $(uname -m) == "ppc64le" ]]; then
    export GOPATH=${TMPDIR:-/tmp}/gopath
    mkdir -p "${GOPATH}"
fi
```

I will need to figure out what the equivalent for this feedstock is...

**Comment by ngam** [comment]
Thanks, it would have taken me hours or days to figure that out 😆

**Comment by isuruf** [comment]
Thanks

**Pull request merged**
