### PR TITLE
Enable branding environment variable inheritance.

### PR DESCRIPTION
**Pull request by bjlittle**
Enable the recipe to inherit the `python_branding` environment variable for customisation within the  `brand_python.py` script.

https://github.com/conda-forge/python-feedstock/blob/master/recipe/brand_python.py#L36

### CODE REVIEW

**Comment by bjlittle** [comment]
@jjhelmus or @msarahan fancy considering this PR? Thanks

**Comment by pelson** [comment]
:+1: - LGTM (but I'm not going to merge due to conflict of interest). @bjlittle - did you also want this for the 2.7 branch?

**Comment by bjlittle** [comment]
@pelson Thanks, I'll also target `2.7` and `3.4` in separate PRs

**Comment by jakirkham** [comment]
All of these seem reasonable to me. Not entirely sure how they would work without this though. Should we wait for @jjhelmus who authored these recipes to double check we aren't missing something obvious or are you happy enough to have them merged now?

**Comment by bjlittle** [comment]
> Not entirely sure how they would work without this though.

@jakirkham Yeah, this is the only way that I can see for the python branding to work. I hope that I'm not missing something obvious (which I'd love to know, if that's the case!)

Thanks

**Comment by bjlittle** [comment]
Ping @jakirkham @msarahan @jjhelmus

**Comment by jjhelmus** [comment]
LGTM. Thanks for putting this together @bjlittle, merging.

**Pull request merged**
