### PR TITLE
Install python_bin in SRC_DIR

### PR DESCRIPTION
**Pull request by xhochy**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xhochy** [comment]
Looks like the move to alma9 breaks the yum requirements:

```
+ /usr/bin/sudo -n yum install -y libX11 libxcb libxau
AlmaLinux 9 - AppStream                         9.0 MB/s | 8.6 MB     00:00    
AlmaLinux 9 - BaseOS                            3.3 MB/s | 3.4 MB     00:01    
AlmaLinux 9 - Extras                             19 kB/s |  13 kB     00:00    
No match for argument: libxau
  * Maybe you meant: libXau
Error: Unable to find a match: libxau
```

**Comment by xhochy** [comment]
To avoid looking into CI logs: It fails in a downstream test for setuptools which wants to install `python=3.9` instead of the one built in this recipe.

**Comment by beckermr** [comment]
Yes the issue is that a `downstream` test might be fore a `noarch: python` package which by default is tested only on `python_min`. There are two fixes, depending on what is more important.

1. Constrain the `downstream` tests in the `upstream` package to only run on `python_min`.
2. Remove the `python_min` requirement from the `downstream` package's test requirements.

More or less, you prefer 1 when testing the `downstream` package on `python_min` is the most important thing. You prefer 2 when testing all python versions of the `upstream` package with the `downstream` package is the most important thing. 

In this case, I suspect 2 is the right choice.

**Comment by beckermr** [comment]
I am going to add this text to our docs for posterity.

**Comment by beckermr** [comment]
xref: https://github.com/conda-forge/conda-forge.github.io/pull/2387

**Comment by xhochy** [comment]
Thank you! Fix is then here: https://github.com/conda-forge/setuptools-feedstock/pull/371

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Pull request merged**
