### PR TITLE
Rerender the 3.6 branch to use clang 9 and vs2017

### PR DESCRIPTION
**Pull request by rggjan**
Trying to get this to work:
https://github.com/conda-forge/python-feedstock/pull/275

by building with vs2017 for windows (https://github.com/conda-forge/python-feedstock/pull/275#issuecomment-551061364)

### CODE REVIEW

**Comment by jschueller** [comment]
maybe use only azure ?
https://github.com/conda-forge/pyside2-feedstock/pull/39/commits/e35ccba747e231fde793e640159b92f485b4eae9

**Comment by jschueller** [comment]
replace 'appveyor' by 'default' in conda-forge.yml and rerender

**Comment by rggjan** [comment]
Thanks! Let's see what happens now...

**Comment by jschueller** [comment]
you must replace appveyor by default in the provider line, then rerender

**Comment by rggjan** [comment]
Hmmm... that didn't seem to help

**Comment by jschueller** [comment]
see:
```
provider: {linux_aarch64: default, linux_ppc64le: default, win: appveyor}
```

**Comment by rggjan** [comment]
Like this?

**Comment by jschueller** [comment]
@conda-forge-admin please rerender

**Comment by rggjan** [comment]
Why does it still run appveyor?

**Comment by jschueller** [comment]
the rerendering failed, can you check the Allow edits from maintainers" box?

**Comment by rggjan** [comment]
This box is checked (and was checked from the beginning...). Not sure what's wrong. Feel free to fork (or merge my changes into your original PR) if this helps...

**Comment by scopatz** [comment]
Appveyor is irrelevant here.

**Comment by scopatz** [comment]
This looks good to me, but I would appreciate more eyes

**Comment by jschueller** [comment]
@conda-forge-admin please rerender

**Comment by isuruf** [comment]
We built 3.6 with VS2015 and why change this now?

**Comment by rggjan** [comment]
It didn't build anymore with vs2015. See this comment by @mariusvniekerk:
https://github.com/conda-forge/python-feedstock/pull/275#issuecomment-551061364

**Comment by rggjan** [comment]
Anyone has another idea how to fix the `AppVeyor build failed`?

**Comment by h-vetinari** [comment]
> Anyone has another idea how to fix the `AppVeyor build failed`?

You can install `conda-smithy` and run `conda smithy rerender` locally (since the bot can't push to your branch). Then you can commit the changes that should remove the AppVeyor job yourself.

**Comment by rggjan** [comment]
Hmm... the `conda-smithy` rerender undid my visual studio changes... how do I make conda-smithy use visual studio 2017?

**Comment by h-vetinari** [comment]
> Hmm... the `conda-smithy` rerender undid my visual studio changes... how do I make conda-smithy use visual studio 2017?

Well, the rerender was only necessary to remove appveyor. Now you could theoretically re-add your VS2017 changes. For making it "rerender-proof", the [README](https://github.com/conda-forge/python-feedstock/tree/master/.ci_support) under `.ci_support` gives a hint:
> This file is automatically generated by conda-smithy.  To change any matrix elements, you should change conda-smithy's input conda_build_config.yaml and re-render the recipe, rather than editing these files directly.

**Comment by isuruf** [comment]
I don't know whether switching from VS2015 to VS2017 is a good idea. For example, what happens to downstream packages? Will they be using VS2017 or VS2015? Will they be compatible?

**Comment by isuruf** [comment]
Besides, https://github.com/conda-forge/python-feedstock/pull/275 works in appveyor with VS2015

**Comment by rggjan** [comment]
> Besides, #275 works in appveyor with VS2015

But why is #275 failing then? And how to fix it?

**Comment by isuruf** [comment]
Done in #275

**Pull request closed without merging**
