### PR TITLE
Update to 3.6.1

### PR DESCRIPTION
**Pull request by ocefpaf**
See https://docs.python.org/3.6/whatsnew/changelog.html#python-3-6-1

### CODE REVIEW

**Comment by jjhelmus** [comment]
Thanks @ocefpaf. I saw the release notice for 3.6.1 this morning but you beat me to the update.  I'll keep an eye on the builds and merge once green.

**Comment by ocefpaf** [comment]
> Thanks @ocefpaf. I saw the release notice for 3.6.1 this morning but you beat me to the update.

I did not mean to steal your :zap: :wink: 
I just got bored waiting for a service on the electric grid in my apartment and did this from my cellphone when I saw the twitter announcement.

> I'll keep an eye on the builds and merge once green.

Thanks!

**Comment by jjhelmus** [comment]
Looks like the Windows build is failing because of https://github.com/conda-forge/conda-forge.github.io/issues/357

**Comment by ocefpaf** [comment]
Yep that is expected since the `rollout builds` was removed in favor of an external layer to do the same :unamused:

**Comment by jjhelmus** [comment]
Closed/Reopened to restart CI now that the curl fix has been merged.

**Comment by jakirkham** [comment]
It will need to be re-rendered with `conda-smithy` 2.2.1. Has that happened somewhere?

**Comment by ocefpaf** [comment]
Jonathan I am on the road (long weekend here, enjoying some :sun: and
:beach:).

Please do whatever is easier for you to get this in or I'll fix it once I
get back.

**Comment by ocefpaf** [comment]
> ~~Please do whatever is easier for you to get this in or I'll fix it once I
get back.~~

Just got some free time and re-rendered this. Should be OK now.

**Comment by jjhelmus** [comment]
Thanks for the re-render @ocefpaf.  All CI are green, merging!

**Pull request merged**
