### PR TITLE
Python 3.4.5

### LINKED ISSUE #3: Python 3.4
Would be nice to build Python 3.4.  

[Source code for Python 3.4.4](https://www.python.org/downloads/release/python-344/)

[anaconda-recipes python-3.4 recipe](https://github.com/ContinuumIO/anaconda-recipes/tree/8e3e7c10c929659e5c7c06a3204a5c081efbfe4c/python-3.4)

### PR DESCRIPTION
**Pull request by jjhelmus**
closes #3

### CODE REVIEW

**Comment by jjhelmus** [comment]
I'm not sure why the win-64 build is failing.  Anyone else interesting in looking at it.  The failure is:

```
     Creating library C:\conda\conda-bld\work\Python-3.4.5\PCbuild\amd64\python34stub.lib and object C:\conda\conda-bld\work\Python-3.4.5\PCbuild\amd64\python34stub.exp
  	cl /LD /FeC:\conda\conda-bld\work\Python-3.4.5\PCbuild\amd64\python3.dll python3dll.c python3.def C:\conda\conda-bld\work\Python-3.4.5\PCbuild\amd64\python34stub.lib
  Microsoft (R) C/C++ Optimizing Compiler Version 16.00.40219.01 for x64
  Copyright (C) Microsoft Corporation.  All rights reserved.
  
  python3dll.c
  Microsoft (R) Incremental Linker Version 10.00.40219.01
  Copyright (C) Microsoft Corporation.  All rights reserved.
  
  /dll 
  /implib:C:\conda\conda-bld\work\Python-3.4.5\PCbuild\amd64\python3.lib 
  /out:C:\conda\conda-bld\work\Python-3.4.5\PCbuild\amd64\python3.dll 
  /def:python3.def 
  python3dll.obj 
  C:\conda\conda-bld\work\Python-3.4.5\PCbuild\amd64\python34stub.lib 
     Creating library C:\conda\conda-bld\work\Python-3.4.5\PCbuild\amd64\python3.lib and object C:\conda\conda-bld\work\Python-3.4.5\PCbuild\amd64\python3.exp
  xxlimited.c
LINK : fatal error LNK1104: cannot open file 'python34.lib' [C:\conda\conda-bld\work\Python-3.4.5\PCbuild\xxlimited.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\Win32\PlatformToolsets\Windows7.1SDK\Microsoft.Cpp.Win32.Windows7.1SDK.targets(20,5): error : You are attempting to build a Win32 application from an x64 environment. If using the Windows 7.1 SDK build environment, type setenv /x86 [C:\conda\conda-bld\work\Python-3.4.5\PCbuild\pylauncher.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\Win32\PlatformToolsets\Windows7.1SDK\Microsoft.Cpp.Win32.Windows7.1SDK.targets(20,5): error : You are attempting to build a Win32 application from an x64 environment. If using the Windows 7.1 SDK build environment, type setenv /x86 [C:\conda\conda-bld\work\Python-3.4.5\PCbuild\pywlauncher.vcxproj]
C:\conda\conda-bld\work\Python-3.4.5\PCbuild>if errorlevel 1 exit 1 
Command failed: C:\Windows\system32\cmd.exe /c call bld.bat
Command exited with code 1
```

**Comment by jjhelmus** [comment]
Apparently `set TARGET_CPU=amd64` needs to be set explicitly for 64 bit builds, [source](http://stackoverflow.com/questions/9314378/visual-c-express-2010-attempting-to-build-a-win32-application-from-an-x64-en).

**Comment by jjhelmus** [comment]
Please do not merge this yet, the test phase is not being run during the Windows build due to a bug in `conda build`.  @msarahan indicated a fix should be available for this shortly.

**Comment by jakirkham** [comment]
> Please do not merge this yet, the test phase is not being run during the Windows build due to a bug in `conda build`.

Went ahead and marked it WIP for that reason.

**Comment by jjhelmus** [comment]
Reopening to trigger a new set of builds which should use the new version of conda-build.

**Comment by jjhelmus** [comment]
Windows tests are running and passing. Removing WIP from this PR.

Everything seems to be in order, please have a review and let me know if I missed anything.

**Comment by ocefpaf** [comment]
LGTM

**Comment by msarahan** [comment]
Thanks!

**Pull request merged**
