### PR TITLE
create manual new python build against libffi=3.3

### PR DESCRIPTION
**Pull request by akrherz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
*  Reset the build number to `0` (if the version changed)
* [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This is perhaps a lame attempt at creating a python3.10 + libffi build combination that other packages could pin against to avoid bugs perhaps with the libffi=3.4 package.  ie #522 

Totally feel free to reject this forcibly, just attempt to be helpful :)

I purposefully did not re-render.

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks Daryl! 😄

As @erykoff came up with a workable solution ( https://github.com/conda-forge/python-feedstock/issues/522#issuecomment-974521764 ), would propose we do that instead. Also would suggest we include the test @mbargull came up with ( https://github.com/conda-forge/python-feedstock/pull/523 )

cc @beckermr (for vis)

**Comment by beckermr** [comment]
My understanding is that 3.3 working is an accident. If apple ever changes what their system version is, things would break again. So @erykoff 's solution is preferred.

**Comment by akrherz** [comment]
> My understanding is that 3.3 working is an accident. If apple ever changes what their system version is, things would break again.

I don't agree.  If the bug is that python got compiled against system libffi, but linked at runtime against conda-forge libffi.  The fact that this build hard codes this runtime link against 3.3 would prevent any future system updates from causing issues.

> So @erykoff 's solution is preferred.

Totally agreed, just sort of nice to have an immediate green alternative :)

**Comment by erykoff** [comment]
I think that Matt's point is not that the build here would break, but that this way of building would break if run on a system that had libffi 3.4.2.

I think it should be very easy to instead to `export PKG_CONFIG=$BUILD_PREFIX/bin/pkg-config` in build_base.sh and that would get this going.

**Comment by akrherz** [comment]
I don't mean to argue or make ignorant noise, but will also note that this

> $ python -c "from ctypes import CFUNCTYPE; CFUNCTYPE(None)(id)"

does not reproduce for me locally on 10.13.6

**Comment by erykoff** [comment]
Yeah, I couldn't get that to crash either.  I was basing my investigations on the crashes in the python ctypes tests.  And putting in debugging statements led to a whole bunch of compiler warnings which led me to the include problem.

**Comment by jakirkham** [comment]
If you would like to add an additional test, that would be welcome :) Ideally it would be something self-contained to `python` (so no other dependencies)

**Comment by isuruf** [comment]
Superceded by #525

**Comment by akrherz** [comment]
Thanks @isuruf , I was about to mark this as a draft :)  It would have been nice to see what CI did though...

**Pull request closed without merging**
