### PR TITLE
Add `python_abi` to `run_constrained` (for 3.6)

### PR DESCRIPTION
**Pull request by jakirkham**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jakirkham** [comment]
Hmm...ok. What should we be doing instead? 🙂

**Comment by isuruf** [comment]
It's a bug/feature of conda solver. We should update this to 3.6.10. Can you click the allow edits from maintainers button?

**Comment by jakirkham** [comment]
Ack! Ok that makes sense. Should we be hot-fixes old `python` packages then? 

I would, but GitHub doesn't show it 😞

**Comment by jakirkham** [comment]
Are there other changes we need?

**Comment by isuruf** [comment]
We need https://github.com/conda-forge/python-feedstock/blob/3.7/recipe/patches/0020-Use-ranlib-from-env-if-env-variable-is-set.patch backported to avoid a bug introduced between 3.6.7 and 3.6.10

**Comment by mbargull** [comment]
> It's a bug/feature of conda solver.

Can you elaborate and/or point me to CI logs?

**Comment by isuruf** [comment]
@mbargull, pypy python version was 3.6.9 and cpython version was 3.6.7. In `current_repodata.json`, only pypy 3.6.9 was there. This means that `conda install python=3.6` was resolved with the pypy python version 3.6.9 even though it has a `track_features` recipe.

**Comment by mbargull** [comment]
Ah, that `current_repodata.json` thing... Makes sense, thank you!

**Comment by jakirkham** [comment]
How do we avoid this issue cropping up in the future?

**Comment by jakirkham** [comment]
Handled in PR ( https://github.com/conda-forge/python-feedstock/pull/323 ).

**Pull request closed without merging**
