### PR TITLE
Fix find_library so that it looks in sys.prefix/lib first

### PR DESCRIPTION
**Pull request by tacaswell**
Conflicts:
	recipe/meta.yaml
	  Many more patches are applied to AnacondaRecipes version

### CODE REVIEW

**Comment by jakirkham** [comment]
Not sure if you did, but we might need [this patch]( https://github.com/AnacondaRecipes/python-feedstock/blob/master-3.5/recipe/0017-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch ) instead of the one in `master`.

**Comment by tacaswell** [comment]
Ah, yup that makes sense (and I'll stop trying to hand edit diff files....)

**Comment by jakirkham** [comment]
Sorry. Should have pointed that out sooner. 😳

**Comment by tacaswell** [comment]
No worries!

**Pull request merged**
