### PR TITLE
Update to 3.10.9

### PR DESCRIPTION
**Pull request by moreshiny**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

### CODE REVIEW

**Comment by moreshiny** [comment]
@conda-forge-admin, please rerender

**Comment by moreshiny** [comment]
@conda-forge-admin, please rerender

**Comment by moreshiny** [comment]
I tried https://github.com/conda-forge/python-feedstock/pull/613/commits/5229087120cf76dad54e0cbd66fbfdf00851f21b but that did not help. I have disabled the downstream setuptools test.

**Comment by isuruf** [comment]
Did you rerender afterwards?

**Comment by moreshiny** [comment]
@conda-forge-admin, please rerender

**Comment by moreshiny** [comment]
> Did you rerender afterwards?

It seems I did not. With the lobsolv patch and rerendering CI passes (setuptools test included).

**Comment by isuruf** [comment]
Thanks

**Pull request merged**
