### PR TITLE
Apply bzip2 shared library fix and rerender recipe - Python 3.5

### PR DESCRIPTION
**Pull request by jjhelmus**

### CODE REVIEW

**Comment by jjhelmus** [comment]
Same as #138 but for Python 3.5

**Comment by jakirkham** [comment]
Guessing we need to borrow commit ( https://github.com/conda-forge/python-feedstock/commit/ebc038014f89a2d2c7a566707be4770bc4a5c9d6 ).

**Comment by jjhelmus** [comment]
> Guessing we need to borrow commit

Yes, I'll pull it in later today.

**Comment by jjhelmus** [comment]
This could use a review, CI are now green.

**Comment by jakirkham** [comment]
Thanks @jjhelmus.

**Pull request merged**
