### PR TITLE
Backport regex fix to 3.6

### PR DESCRIPTION
**Pull request by SylvainCorlay**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jjhelmus** [comment]
@conda-forge-admin, please rerender

**Comment by SylvainCorlay** [comment]
I don't know what's up with the CI on appveyor, but this seems unrelated to us.

**Comment by jjhelmus** [comment]
LGTM.  Going to close and re-open to hopefully re-trigger CI.

**Comment by SylvainCorlay** [comment]
@jjhelmus there seems to be an issue on appveyor over

```
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by SylvainCorlay** [comment]
@conda-forge-admin, please rerender

**Comment by SylvainCorlay** [comment]
@jjhelmus @isuruf this is ready to go!

**Comment by SylvainCorlay** [comment]
@conda-forge/core this is ready to go.

This is a backport of #331 to Pyton 3.6, which was already backported to Python 3.7 in #333.

**Comment by SylvainCorlay** [comment]
Thanks!

**Comment by SylvainCorlay** [comment]
It seems that the Appveyor build timed out, preventing the windows builds to be uploaded.

**Pull request merged**
