### PR TITLE
Fix brand regex

### PR DESCRIPTION
**Pull request by SylvainCorlay**
Fixes #194 

**I would really advocate from completely removing the `brand_python.py` though. I don't think that modifying `_sys_version` is a clean way of changing the banner.**

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
This windows build failure appears to be unrelated to that change:

```
ERROR conda.core.link:_execute(568): An error occurred while installing package 'conda-forge::pkginfo-1.5.0.1-py_0'.
CondaError: Cannot link a source that does not exist. C:\Miniconda\Scripts\conda.exe
```

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by SylvainCorlay** [comment]
Even if this works, I think we should consider completely removing that patch.

**Comment by jjhelmus** [comment]
I'm fine removing this patch entirely.  It was in conda-forge before I started working on the python recipe so I kept it.

**Comment by mingwandroid** [comment]
What about using the anaconda branding mechanism instead? We change the c code. I can template the patch and apply the correct replacement at build time if that's acceptable?

Branding is kinda useful if you change things significantly and I think, for better or worse we do that. But I don't mind if we remove it entirely for conda-forge either really.

**Comment by jakirkham** [comment]
Having some kind of branding is useful I think. Though I don't know if we are discussing removing it or just some minor tweaks at this point.

**Comment by SylvainCorlay** [comment]
> What about using the anaconda branding mechanism instead? We change the c code. I can template the patch and apply the correct replacement at build time if that's acceptable?

I don't know where to find that recipe?

**Comment by SylvainCorlay** [comment]
> Having some kind of branding is useful I think. Though I don't know if we are discussing removing it or just some minor tweaks at this point.

This PR does a minor tweak but I was suggesting we should consider removing it completely.

**Comment by SylvainCorlay** [comment]
For your information, I opened #332 completely removing the patching of `sys.version` - and which I think preferable over this approach.

**Comment by SylvainCorlay** [comment]
Any interest in getting this in?

**Comment by isuruf** [comment]
Can you bump the build number?

**Comment by SylvainCorlay** [comment]
> Can you bump the build number?

Done

**Comment by SylvainCorlay** [comment]
@isuruf  I bumped the build number - and did some more testing locally.

**Comment by SylvainCorlay** [comment]
The rerender seems to be problematic. I don't see why there should be a `linux_python3.7` build of Python 3.8...

**Comment by isuruf** [comment]
One build in linux-64 passing is enough

**Pull request merged**
